### ISSUE TITLE
Cannot read property 'class_loaded' of null

### ISSUE THREAD

**Issue by wzhscript** [verlok/lazyload#397]
**Describe the bug**

Error when destroyed and loading was not finished

**To Reproduce**

1. Go to  here https://output.jsbin.com/nirokam/20;
2. Open Chrome DevTools, disable cache, and switch to Slow 3G;
3. Refresh page;
4. See error in the console tab
![image](https://user-images.githubusercontent.com/5771319/69424129-d0d81680-0d62-11ea-9804-832114d6278d.png)

**Expected behavior**

when destroyed, loading should finish normally

**LazyLoad version**

Please report which version of LazyLoad you're using.
- Version 12.0.0

**Additional context**

The error is caused by [this line of code](https://github.com/verlok/lazyload/blob/12.0.0/src/lazyload.event.js#L31) , since the lazyload instance is [destroyed](https://github.com/verlok/lazyload/blob/12.0.0/src/lazyload.js#L41)  before some images finish loading.

**Comment by wzhscript** [comment]
Mybe I can wait until all images are loaded, then call destroy(), like this:

```
function destroy() {
    if (lazyload._loadingCount === 0) {
        lazyload.destroy();
    }
    else {
        setTimeout(destroy, 100);
    }
}
setTimeout(destroy, 100);
```

But the _loadingCount is private, it will be perfect to have a public interface to know if no image is still loading.

**Comment by wzhscript** [comment]
Another solution is to change the [destroy method](https://github.com/verlok/lazyload/blob/12.0.0/src/lazyload.js#L33).

```
{
    ...
    destroy: function() {
		if (this._observer) {
			this._elements.forEach(element => {
				this._observer.unobserve(element);
			});
			this._observer = null;
		}
		// this._elements = null;
		// this._settings = null;
	},
        ...
}
```
`_elements` and `_settings` should not be unset, since they are referenced in handler of image load event.

**Comment by verlok** [comment]
Hey @wzhscript, 
thank you for opening this and for the ideas.

Can I ask you a question? Why do you need to destroy the LazyLoad instance if the loading is not finished yet? FYI the script already unsets the IntersectionObserver when the loading of all images has finished.

Anyway, the idea of making the `_loadingCount` property public is very good and I'll think about it.

**Comment by eugene-stativka** [comment]
Hi @verlok! I think a good use case for destroying LazyLoad instances is SPA with a client-side routing an a quick navigation from one route to another. There is potential situation when images from the first route are not loaded yet and after transition to the second route respective image elements are destroyed but LazyLoad instances are not.

**Comment by verlok** [comment]
By the way, your demo seems to be working correctly on Firefox.

![Your demo on Firefox](https://user-images.githubusercontent.com/1127721/75139079-0dae0380-56ec-11ea-955c-55352fb1ca6b.png)

So it's probably a Chromium bug. 

I suggest you to [file a bug to the Chromium project](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by verlok** [comment]
You're 100% right. I'll see what I can do to solve this problem. Thanks.

**Comment by verlok** [comment]
**Released 12.5.0 with the public `loadingCount` property.**

I also implemented a delayed destroy in the `demos/destroy.html` demo, like the following:

```
destroyButton.addEventListener("click", () => {
    destroyButton.disabled = true;
    destroyButton.innerText = "Waiting...";
    const destroyInterval = setInterval(() => {
        if (ll.loadingCount > 0) return; // EXIT CONDITION
        clearInterval(destroyInterval);
        ll.destroy();
        ll = null;
        destroyButton.innerText = "Destroyed";
    }, 250);
});
```

➡ [**Try this online**](https://www.andreaverlicchi.eu/lazyload/demos/destroy.html)

**Comment by eugene-stativka** [comment]
Seems like the issue is still there for SPAs. `Uncaught TypeError: Cannot read property 'class_loaded' of null` ([this line](https://github.com/verlok/lazyload/blob/master/src/lazyload.event.js#L31)). The same problem will occur in all places where `instance.someProperty` is used because all properties are nullable. Either we should check every property before using it OR we should find another solution. Maybe something like setting `isDestroyed` flag.

**Comment by englishextra** [comment]
@eugene-stativka 
@verlok 
![2020-10-03_213533](https://user-images.githubusercontent.com/537127/94999229-bdbbe700-05c0-11eb-9f89-1489ba6125b9.jpg)
