### ISSUE TITLE
Not working on Internet Explorer 8

### ISSUE THREAD

**Issue by peritpatrio** [verlok/lazyload#5]
**Steps to reproduce**

1. Open IE8
2. Go to http://verlok.github.io/lazyload/demos/simple.html
3. Images will not load

![image](https://cloud.githubusercontent.com/assets/729565/7831029/4dad2cba-045b-11e5-8163-71884a9ec049.png)

**Comment by verlok** [comment]
I'm gonna check this today. Hold on!

**Comment by verlok** [comment]
The bug is caused by a code refactoring that @brunoscopelliti did and we released in v1.5.0. Please download v1.4.2 from [here](https://github.com/verlok/lazyload/releases/tag/v1.4.2) if you need an immediate solution. We're going to fix this soon and release 1.5.1.

**Comment by peritpatrio** [comment]
Thanks @verlok for the fast response!

**Comment by peritpatrio** [comment]
I might be wrong, but it does not seem to be working in 1.4.2 either:

![image](https://cloud.githubusercontent.com/assets/729565/7879246/706cacd8-05f7-11e5-8c60-f87ec577888c.png)

**Comment by peritpatrio** [comment]
If it helps, I'm using both `data-original` and `data-original-set` in the images.

**Comment by verlok** [comment]
I noticed that, hold on, the fix is coming!

**Comment by verlok** [comment]
Fixed! See https://github.com/verlok/lazyload/releases/tag/v1.5.1

**Comment by peritpatrio** [comment]
I'm afraid that I'm still having problems:

![image](https://cloud.githubusercontent.com/assets/729565/7902944/a772fb86-07d4-11e5-9084-189829cd52bd.png)

These errors come up with when opening and scrolling `/demos/with_srcset.html` in the latest release.

**Comment by verlok** [comment]
Fixed again. Please check and close issue if you agree. https://github.com/verlok/lazyload/releases/tag/v1.5.3

**Comment by verlok** [comment]
@peritpatrio waiting for your approval :)

**Comment by peritpatrio** [comment]
Seems to be working now. Thank you @verlok!
